# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64949723c33c2d893b80547f543e1b3bec03ec80f39dc8a7548e6431b959418cb6d3c5a57899e1d5b63afb7f2fe61ad61f1f991f64e8b0b7b243e9dbc999715

test:
  secret_key_base: 8a2222ca7dd207a095c0a5d3fdff799d7eebb8f49cf1340080a20087104470140de4f746d874f2f80e038b6f5733f400ad157f5a03d398443a5d57786d63d787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
